### ISSUE TITLE
Add select and multi select form inputs

### ISSUE THREAD

**Issue by ad-si** [passiomatic/elm-designer#64]
I wanted to build an app and this was literally the first thing I looked for, but it seems to be missing? 😅

**Comment by passiomatic** [comment]
if your are looking for something like `<select>`, it is missing because is intentionally omitted from Elm UI too, see https://discourse.elm-lang.org/t/input-select-not-available-in-elm-ui/2874/5?u=passiomatic . Right now Elm Designer tends to be a 1:1 mapping on Elm UI so at this stage it makes sense to follow its API as much as possible. 

There's a myriad of alternative picker, dropdown, multi-select widgets for Elm, everyone with its own API. So your best bet is to do a little analysis on your requirements plug it in directly bypassing Elm Designer.

**Comment by passiomatic** [comment]
I'm closing this since in Elm UI using `select` is discouraged.
