### ISSUE TITLE
Add undo/redo commands

### ISSUE THREAD

**Issue by CharlonTank** [passiomatic/elm-designer#7]
It happened to me to remove what I've done by pressing 4 times backspaces to remove a text but I selected the field. I had 20 minutes of work disappeared haha.

I know this is early beta but this has to be done for sure ;)

**Comment by passiomatic** [comment]
Thank you for the feedback. Yes, this is planned, a few days ago I was looking at https://package.elm-lang.org/packages/elm-community/undo-redo/latest/UndoList that seems to fit perfectly.

**Comment by CharlonTank** [comment]
I implemented a simple Undo button and it's working like a charm! Will PR ASAP :)

**Comment by passiomatic** [comment]
Glad it is straightforward as I thought!  Basically every changes that it is worthwhile should be recorded as such in the `UndoList`. 

As you have seen already all the style/property changes are done by `Main.elm`'s `applyChange` and `applyChangeAndFinish`  functions, plus there are the page add/deletion and node creation/deletion scenarios. All these should make `UndoList` to advance.

## About Electron menu 

One thing that is really annoying is the way Electron manages of the app menu. It is very "imperative" and every change to it need to trigger a port command to the renderer Electron process. Then the _renderer_ process (which is the one running the Elm code) can change app `MenuItem` status via the `remote` object (ha!) which call the _main_ Electron process – this at least spares us on extra roundtrip via Electron IPC. 

All this to say that app Edit -> "Undo" and "Redo" items should be enabled or disabled accordingly to the `UndoList` state. Since I need to manage the menu items for other purposes I'm thinking on an elegant way to "bind" certain command status to the corresponding MenuItem status. 

## Your question 

> ...would it makes more sense to have a undo redo per page?

Good catch. My gut feeling is that if you make a change on one page, then you switch to another page, do a second change, and you finally hit two times undo you have to _see_ what you are un-doing. If we keep the UndoList global there's the possibility to "hide" the visible history behind one page or another.  

So I can see two options: 

1. Keep `UndoList` global, but record page switch too into the `UndoList` itself. [Sketch](https://www.sketch.com) app do this. This is quite astute and if I read your comment correctly that's how you coded it.
2. Split UndoLists, one per page, as you already have suggested. This is probably a less surprising behavior and the more safe way to do it.  For the record [Figma](https://www.figma.com), and VS Code, and [you name it] do this. 

So probably the second one is the way to go and of course is more complex. 😀

**Comment by CharlonTank** [comment]
Thank you for your answer, fyi, Figma, like Sketch uses the first option too.

I'm gonna leave this like that for now.
If I really see that this global UndoList is annoying when editing multiple files (like we all do in VS-Code for example), I will change it to the second option.

#Mandatory improvements - Shorcuts

I'm trying to see how to do the cmd/ctrl+Z and the cmd/ctrl+shift+Z key presses to be able to undo/redo.

**Comment by passiomatic** [comment]
Oh, I was trying Figma yesterday but I was using different _files_ (tabs in the UI) not _pages_.  Based on your findings it seems not so strage having  the undo history shared among pages.

**Comment by CharlonTank** [comment]
https://github.com/passiomatic/elm-designer/pull/15
